import { StyleRules } from "./withStyles";

import { AppBarClassKey } from "../AppBar";
import { AvatarClassKey } from "../Avatar";
import { BackdropClassKey } from "../Backdrop";
import { BadgeClassKey } from "../Badge";
import { BottomNavigationActionClassKey } from "../BottomNavigationAction";
import { BottomNavigationClassKey } from "../BottomNavigation";
import { BreadcrumbsClassKey } from "../Breadcrumbs";
import { ButtonBaseClassKey } from "../ButtonBase";
import { ButtonClassKey } from "../Button";
import { ButtonGroupClassKey } from "../ButtonGroup";
import { CardActionAreaClassKey } from "../CardActionArea";
import { CardActionsClassKey } from "../CardActions";
import { CardClassKey } from "../Card";
import { CardContentClassKey } from "../CardContent";
import { CardHeaderClassKey } from "../CardHeader";
import { CardMediaClassKey } from "../CardMedia";
import { CheckboxClassKey } from "../Checkbox";
import { ChipClassKey } from "../Chip";
import { CircularProgressClassKey } from "../CircularProgress";
import { CollapseClassKey } from "../Collapse";
import { ContainerClassKey } from "../Container";
import { CssBaselineClassKey } from "../CssBaseline";
import { DialogActionsClassKey } from "../DialogActions";
import { DialogClassKey } from "../Dialog";
import { DialogContentClassKey } from "../DialogContent";
import { DialogContentTextClassKey } from "../DialogContentText";
import { DialogTitleClassKey } from "../DialogTitle";
import { DividerClassKey } from "../Divider";
import { DrawerClassKey } from "../Drawer";
import { ExpansionPanelActionsClassKey } from "../ExpansionPanelActions";
import { ExpansionPanelClassKey } from "../ExpansionPanel";
import { ExpansionPanelDetailsClassKey } from "../ExpansionPanelDetails";
import { ExpansionPanelSummaryClassKey } from "../ExpansionPanelSummary";
import { FabClassKey } from "../Fab";
import { FilledInputClassKey } from "../FilledInput";
import { FormControlClassKey } from "../FormControl";
import { FormControlLabelClassKey } from "../FormControlLabel";
import { FormGroupClassKey } from "../FormGroup";
import { FormHelperTextClassKey } from "../FormHelperText";
import { FormLabelClassKey } from "../FormLabel";
import { GridClassKey } from "../Grid";
import { GridListClassKey } from "../GridList";
import { GridListTileBarClassKey } from "../GridListTileBar";
import { GridListTileClassKey } from "../GridListTile";
import { IconButtonClassKey } from "../IconButton";
import { IconClassKey } from "../Icon";
import { InputAdornmentClassKey } from "../InputAdornment";
import { InputBaseClassKey } from "../InputBase";
import { InputClassKey } from "../Input";
import { InputLabelClassKey } from "../InputLabel";
import { LinearProgressClassKey } from "../LinearProgress";
import { LinkClassKey } from "../Link";
import { ListClassKey } from "../List";
import { ListItemAvatarClassKey } from "../ListItemAvatar";
import { ListItemClassKey } from "../ListItem";
import { ListItemIconClassKey } from "../ListItemIcon";
import { ListItemSecondaryActionClassKey } from "../ListItemSecondaryAction";
import { ListItemTextClassKey } from "../ListItemText";
import { ListSubheaderClassKey } from "../ListSubheader";
import { MenuClassKey } from "../Menu";
import { MenuItemClassKey } from "../MenuItem";
import { MobileStepperClassKey } from "../MobileStepper";
import { NativeSelectClassKey } from "../NativeSelect";
import { OutlinedInputClassKey } from "../OutlinedInput";
import { PaperClassKey } from "../Paper";
import { PopoverClassKey } from "../Popover";
import { RadioClassKey } from "../Radio";
import { SelectClassKey } from "../Select";
import { SliderClassKey } from "../Slider";
import { SnackbarClassKey } from "../Snackbar";
import { SnackbarContentClassKey } from "../SnackbarContent";
import { StepButtonClasskey } from "../StepButton";
import { StepClasskey } from "../Step";
import { StepConnectorClasskey } from "../StepConnector";
import { StepContentClasskey } from "../StepContent";
import { StepIconClasskey } from "../StepIcon";
import { StepLabelClasskey } from "../StepLabel";
import { StepperClasskey } from "../Stepper";
import { SvgIconClassKey } from "../SvgIcon";
import { SwitchClassKey } from "../Switch";
import { TabClassKey } from "../Tab";
import { TableBodyClassKey } from "../TableBody";
import { TableCellClassKey } from "../TableCell";
import { TableContainerClassKey } from "../TableContainer";
import { TableClassKey } from "../Table";
import { TableFooterClassKey } from "../TableFooter";
import { TableHeadClassKey } from "../TableHead";
import { TablePaginationClassKey } from "../TablePagination";
import { TableRowClassKey } from "../TableRow";
import { TableSortLabelClassKey } from "../TableSortLabel";
import { TabsClassKey } from "../Tabs";
import { TextFieldClassKey } from "../TextField";
import { ToolbarClassKey } from "../Toolbar";
import { TooltipClassKey } from "../Tooltip";
import { TouchRippleClassKey } from "../ButtonBase/TouchRipple";
import { TypographyClassKey } from "../Typography";

export type Overrides = {
  [Name in keyof ComponentNameToClassKey]?: Partial<
    StyleRules<ComponentNameToClassKey[Name]>
  >;
};

export interface ComponentNameToClassKey {
  SquiAppBar: AppBarClassKey;
  SquiAvatar: AvatarClassKey;
  SquiBackdrop: BackdropClassKey;
  SquiBadge: BadgeClassKey;
  SquiBottomNavigation: BottomNavigationClassKey;
  SquiBottomNavigationAction: BottomNavigationActionClassKey;
  SquiBreadcrumbs: BreadcrumbsClassKey;
  SquiButton: ButtonClassKey;
  SquiButtonBase: ButtonBaseClassKey;
  SquiButtonGroup: ButtonGroupClassKey;
  SquiCard: CardClassKey;
  SquiCardActionArea: CardActionAreaClassKey;
  SquiCardActions: CardActionsClassKey;
  SquiCardContent: CardContentClassKey;
  SquiCardHeader: CardHeaderClassKey;
  SquiCardMedia: CardMediaClassKey;
  SquiCheckbox: CheckboxClassKey;
  SquiChip: ChipClassKey;
  SquiCircularProgress: CircularProgressClassKey;
  SquiCollapse: CollapseClassKey;
  SquiContainer: ContainerClassKey;
  SquiCssBaseline: CssBaselineClassKey;
  SquiDialog: DialogClassKey;
  SquiDialogActions: DialogActionsClassKey;
  SquiDialogContent: DialogContentClassKey;
  SquiDialogContentText: DialogContentTextClassKey;
  SquiDialogTitle: DialogTitleClassKey;
  SquiDivider: DividerClassKey;
  SquiDrawer: DrawerClassKey;
  SquiExpansionPanel: ExpansionPanelClassKey;
  SquiExpansionPanelActions: ExpansionPanelActionsClassKey;
  SquiExpansionPanelDetails: ExpansionPanelDetailsClassKey;
  SquiExpansionPanelSummary: ExpansionPanelSummaryClassKey;
  SquiFab: FabClassKey;
  SquiFilledInput: FilledInputClassKey;
  SquiFormControl: FormControlClassKey;
  SquiFormControlLabel: FormControlLabelClassKey;
  SquiFormGroup: FormGroupClassKey;
  SquiFormHelperText: FormHelperTextClassKey;
  SquiFormLabel: FormLabelClassKey;
  SquiGrid: GridClassKey;
  SquiGridList: GridListClassKey;
  SquiGridListTile: GridListTileClassKey;
  SquiGridListTileBar: GridListTileBarClassKey;
  SquiIcon: IconClassKey;
  SquiIconButton: IconButtonClassKey;
  SquiInput: InputClassKey;
  SquiInputAdornment: InputAdornmentClassKey;
  SquiInputBase: InputBaseClassKey;
  SquiInputLabel: InputLabelClassKey;
  SquiLinearProgress: LinearProgressClassKey;
  SquiLink: LinkClassKey;
  SquiList: ListClassKey;
  SquiListItem: ListItemClassKey;
  SquiListItemAvatar: ListItemAvatarClassKey;
  SquiListItemIcon: ListItemIconClassKey;
  SquiListItemSecondaryAction: ListItemSecondaryActionClassKey;
  SquiListItemText: ListItemTextClassKey;
  SquiListSubheader: ListSubheaderClassKey;
  SquiMenu: MenuClassKey;
  SquiMenuItem: MenuItemClassKey;
  SquiMobileStepper: MobileStepperClassKey;
  SquiNativeSelect: NativeSelectClassKey;
  SquiOutlinedInput: OutlinedInputClassKey;
  SquiPaper: PaperClassKey;
  SquiPopover: PopoverClassKey;
  SquiRadio: RadioClassKey;
  SquiSelect: SelectClassKey;
  SquiSlider: SliderClassKey;
  SquiSnackbar: SnackbarClassKey;
  SquiSnackbarContent: SnackbarContentClassKey;
  SquiStep: StepClasskey;
  SquiStepButton: StepButtonClasskey;
  SquiStepConnector: StepConnectorClasskey;
  SquiStepContent: StepContentClasskey;
  SquiStepIcon: StepIconClasskey;
  SquiStepLabel: StepLabelClasskey;
  SquiStepper: StepperClasskey;
  SquiSvgIcon: SvgIconClassKey;
  SquiSwitch: SwitchClassKey;
  SquiTab: TabClassKey;
  SquiTable: TableClassKey;
  SquiTableBody: TableBodyClassKey;
  SquiTableCell: TableCellClassKey;
  SquiTableContainer: TableContainerClassKey;
  SquiTableFooter: TableFooterClassKey;
  SquiTableHead: TableHeadClassKey;
  SquiTablePagination: TablePaginationClassKey;
  SquiTableRow: TableRowClassKey;
  SquiTableSortLabel: TableSortLabelClassKey;
  SquiTabs: TabsClassKey;
  SquiTextField: TextFieldClassKey;
  SquiToolbar: ToolbarClassKey;
  SquiTooltip: TooltipClassKey;
  SquiTouchRipple: TouchRippleClassKey;
  SquiTypography: TypographyClassKey;
}
